### ISSUE TITLE
Resetting range via double click alters st.session_state parameters temporarily

### ISSUE THREAD

**Issue by ERafaelMartinez** [fabianandresgrob/streamlit-preserve-zoom-component#1]
Hi! First of all, thank you a lot for the contribution to the streamlit components, it has come very handy for the project I'm currently working on.

I was unsure of how to name the issue, as I do not really understand what could be behind it.

In short, when double clicking on the plot, somehow the application looses temporarily the context of the `session_state`, and some AttributeErrors are raised. In this case, the attribute it looks for is called "current_page". The error logs as follows:

```
2023-06-27 11:34:35.602 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\mart\AppData\Local\pypoetry\Cache\virtualenvs\sbp_sonne_-_fft_analysis-IYx0_w8E-py3.11\Lib\site-packages\streamlit\runtime\state\session_state_proxy.py", line 119, in __getattr__
    return self[key]
           ~~~~^^^^^
  File "C:\Users\mart\AppData\Local\pypoetry\Cache\virtualenvs\sbp_sonne_-_fft_analysis-IYx0_w8E-py3.11\Lib\site-packages\streamlit\runtime\state\session_state_proxy.py", line 90, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\mart\AppData\Local\pypoetry\Cache\virtualenvs\sbp_sonne_-_fft_analysis-IYx0_w8E-py3.11\Lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 111, in __getitem__
    raise KeyError(key)
KeyError: 'current_page'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mart\AppData\Local\pypoetry\Cache\virtualenvs\sbp_sonne_-_fft_analysis-IYx0_w8E-py3.11\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\mart\Workspace\sbp_sonne-fft_analysis\app.py", line 24, in <module>
    main()
  File "C:\Users\mart\Workspace\sbp_sonne-fft_analysis\app.py", line 20, in main
    PAGES[st.session_state.current_page]()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mart\AppData\Local\pypoetry\Cache\virtualenvs\sbp_sonne_-_fft_analysis-IYx0_w8E-py3.11\Lib\site-packages\streamlit\runtime\state\session_state_proxy.py", line 121, in __getattr__
    raise AttributeError(_missing_attr_error_message(key))
AttributeError: st.session_state has no attribute "current_page". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization
```

I should say that this error is raised although the attribute was initialized.

This does not makes the app to crash though, because afterwards everything works as it should. 

As extra information, resetting the plot range via the "autoscale" button on the widget, do not raises any error whatsoever.

Therefore I guess this could be an issue on how the component deals with the double clicking. 

Although this uncaught exception does not cause the app to be unusable, I still wanted to create the issue to provide this short feedback!

Let me know if I can be of further help for debugging this.

**Comment by fabianandresgrob** [comment]
Hi @ERafaelMartinez!
Thank you so much for your feedback and interest in my tiny, little component! :)
So far from your error messages, it seems like this isn't a problem of the component itself. The component never accesses the pages or any other elements in a streamlit app, it's pretty much pure React code combined with the streamlit wrapper.
If you don't mind, could you share some of your code in your `app.py` file? I can have a closer look :)
Maybe it's just a problem of streamlit itself; streamlit reloads the whole app as soon as the session state changes. Therefore, as soon as you zoom out, the whole app is reloaded which may causes the errors you are describing. 

Anyways, feel free to share some code and I'll have a closer look. :)

**Comment by fabianandresgrob** [comment]
Closing due to inactivity
